Card 120824
Eirbware/decouverte-open-source pull request #2
Opened 2024-08-13 22:43 UTC by damdam166

First version of the cards, with hover effect. The media queries is not tested, I think it does not work quite well. The colors should be changed.

2024-08-13 23:23 UTC, NemoDacremont commented
When adding a lot of students, the cards overlaps on the header

![image](https://github.com/user-attachments/assets/7c4a9345-4683-4359-aea3-3a66fa5426fe)

When using a phone, the cards are too wide

![image](https://github.com/user-attachments/assets/4c8c969c-88ab-4e86-85e3-9ae33a6aabdd)

2024-08-14 08:30 UTC, Alexinfos requested changes
It's pretty good overall. I've made some comments directly on files that need some changes. Here are a few other things :

- You should try to rename your classes to follow the  [BEM naming convention](https://en.bem.info/methodology/naming-convention/). For example, the `Picture-120824` class could be renamed to `card-120824__picture`

- If you want to, you can also try learning about the CSS grid layout by using it for the card, which is a quite powerful tool (although maybe a little harder to master than flexbox). This would allow you to get rid of the `Container-120824` div that only exists for styling purposes

2024-08-14 08:30 UTC, Alexinfos commented on css/style_card.css
> +}
The rules defined in this media query don't apply to any element on the page. To make them apply, you should change the class name in the selectors to have them match the class name of elements on the page (e.g. replace `.card` with `.Card-120824`).

Another thing you should change here is the media query condition. You're only applying this specific style when the device's width is less than or equal to 500 pixels, but with a screen width between 500 and 700 pixels, your `.Card-120824` element already extends beyond the viewport. I suggest you bring the `max-width` condition to 720 pixels (to keep some small margins on the sides) or create multiple media queries for more gradual scaling.

2024-08-14 16:55 UTC, Alexinfos requested changes

2024-08-14 16:55 UTC, Alexinfos commented on css/style_card.css
> +    }
This doesn't seem right, I think it should be applied to `card-120824__picture` instead of `Container-120824`

2024-08-14 16:55 UTC, Alexinfos commented on css/style_card.css
> +    background-color: rgba(0, 0, 0, 0); /* transparent color. */
This declaration can be removed (background is transparent by default)

2024-08-17 18:12 UTC, Alexinfos approved these changes

2024-08-17 18:40 UTC, merged